services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=STOBASPD
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@basicstore.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
    - 5050:80